---
- name: Check zabbix repository status
  shell: yum-config-manager zabbix | grep -q 'enabled = True'
  changed_when: False
  ignore_errors: True
  register: zabbix_status
  when: ansible_distribution == "Amazon" or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Check zabbix repository status
  shell: yum-config-manager --dump zabbix | grep -q 'enabled = 1'
  changed_when: False
  ignore_errors: True
  register: zabbix_status
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8"

- name: Install zabbix repository
  yum:
    name: http://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
    state: present
  when: (ansible_distribution == "Amazon" and zabbix_status.rc != 0) or (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7" and zabbix_status.rc != 0)

- name: Install zabbix repository
  yum:
    name: http://repo.zabbix.com/zabbix/5.0/rhel/8/x86_64/zabbix-release-5.0-1.el8.noarch.rpm
    state: present
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "8" and zabbix_status.rc != 0

- name: Enabled zabbix repository
  command: yum-config-manager --enable zabbix
  when:
    - zabbix_status.rc != 0
